# API 参考 https://ollama.apidog.io/

### 获取模型列表

GET /api/tags HTTP/1.1
Host: localhost:11434

### 非流式传输

POST /api/chat HTTP/1.1
Host: localhost:11434
Content-Type: application/json

{
  "model": "deepseek-r1:1.5b",
  "messages": [
    {
      "role": "user",
      "content": "你好"
    }
  ],
  "stream": false
}

### 流式传输

POST /api/chat HTTP/1.1
Host: localhost:11434
Content-Type: application/json

{
  "model": "deepseek-r1:1.5b",
  "messages": [
    {
      "role": "user",
      "content": "你好"
    }
  ],
  "stream": true
}
